// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnfbsdvexekbmnywxydw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZmJzZHZleGVrYm1ueXd4eWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDA3ODYsImV4cCI6MjA2Mjk3Njc4Nn0.3ZyBKacL5HOJpDo1tHGNOnKJh5__GwxMBuwiJYJYoeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);